defaults: &DEFAULTS
  domain: bps.herokuapp.com
  email_domain: bps.herokuapp.com
  protocol: https

development:
  <<: *DEFAULTS
  domain: localhost
  protocol: http
  port: 3000

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS