defaults: &DEFAULTS
  domain: bps.herokuapp.com
  email_domain: bps.herokuapp.com
  protocol: https
  source: 
    code: https://github.com/matholroyd/bps
    readme: https://github.com/matholroyd/bps#readme

development:
  <<: *DEFAULTS
  domain: localhost
  protocol: http
  port: 3000

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS