production:
  adapter: postgresql
  database: bps_production
  username: <%= `whoami` %>

development:
  adapter: postgresql
  database: bps_development
  username: <%= `whoami` %>

test:
  adapter: postgresql
  database: bps_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= `whoami` %>
